### ISSUE TITLE
merge theme/_config into _config?

### ISSUE THREAD

**Issue by icylogic** [icylogic/carbon#13]
like options for disqus or duoshuo.
- Standalone: 
  - flexible
  - default values
- Share:
  - compatible with other themes

**Comment by thinkingofmaud** [comment]
I think disqus and duoshuo should be on the main blog config, not on the theme. It makes more sense that way, since config.disqus_shortname is the 'standard' and works with all themes that support it.

But I noticed the other themes with duoshuo support mainly use theme.duoshuo or even a boolean theme.duoshuo with another handle for the duoshuo id.

**Comment by icylogic** [comment]
OK. I agree that disqus_shortname and duoshuo_shortname should be in the main config. 

And I've been considering how do we deal with the condition that both exist and not void? An additional switch?

**Comment by thinkingofmaud** [comment]
Well, I checked the hexo documentation: **theme inherits from config**. So the code works with theme.duoshuo even if we "only" have config.duoshuo. I even tested it, it works. Clever!

So maybe that is why the chinese themes with duoshuo support all use theme.duoshuo or/and theme.duoshuo_id.
I think you should keep the code as is, but perhaps you may change the handle.
