### ISSUE TITLE
out-site

### ISSUE THREAD

**Issue by thinkingofmaud** [icylogic/carbon#16]
https://github.com/icylogic/carbon/blob/master/layout/_partial/footer.jade#L15-L20

Why do you have a class like that on the outer links? It's a SEO thing?

At first I thought it was about the pjax..

**Comment by icylogic** [comment]
The `out-site` class was defined for adjusting the style for the external links at first. At the moment, we just use `a` to set styles ([unique.styl](https://github.com/icylogic/carbon/blob/master/source/css/_partial/unique.styl#L93-L94)) for these links since there is no other links in the footer, so this class is redundant and could be moved for the moment, or we could modify unique.styl to match these links precisely.
